### ISSUE TITLE
ssh上传文件到路由器的方法（scp失效）

### ISSUE THREAD

**Issue by aparangement** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#105]
scp 报错：
`sh: scp: not found`

windows powershell 或者Ubuntu上尝试了都是这个报错，估计因为路由器系统里没有安装scp。。

请问除了scp之外，有没有从电脑上传文件到路由器的方法？需要离线安装。。

**Comment by JACK-THINK** [comment]
在电脑上安装Everything，`选项-ETP/FTP 服务器`，选中`启用 ETP/FTP 服务器`和`允许 FTP 文件下载`。找到需要传输的文件，右击，`复制完整路径和文件名`

用SSH登录路由器，进入`/tmp`目录，输入`ftpget <电脑IP地址> <文件名> '<粘贴前述完整路径和文件名>'`。注意：`<>`不保留，`'`必须保留
