### ISSUE TITLE
路由器重启后因获取不到script_usbmount无法加载环境

### ISSUE THREAD

**Issue by kunki** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#108]
今天路由器重启后始终无法加载环境，经过仔细调试启动脚本，发现nvram get script_usbmount和nvram get script_usbumount拿到的结果是空的，然而usb_ext_opt、sbl_username、sbl_password这几个变量是有值的。

于是我用restore脚本恢复配置，但也无效。
仔细研究发现，用nvram set重新赋值script_usbmount和script_usbumount两个变量，过一会儿（不到5秒）它们就自动清空了，但是赋值其他变量却可以一直保留。如下图：
![8e56b7606ddb154bb4417de2b94995d9](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/assets/2331180/1edf9adf-8bf8-4fe8-a713-cdcd0a18e9a8)

请问各位大神有解决思路么？

ps：我最近没更新固件，官方固件版本为3.0.0.4.386_51529，路由器型号为RT-AC86U

**Comment by JACK-THINK** [comment]
在2023年9月以后的原厂固件中，华硕官方以“防止恶意代码，增强安全性”为由，强行禁用了`script_usbmount`和`script_usbumount`变量，此问题[无解](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/issues/106#issuecomment-1890837042)，只能转用梅林固件。

如果使用的是旧版固件，建议重置路由器系统并重新部署本系统。
