### ISSUE TITLE
挂载后/tmp/mnt/ASUS_ROUTER为只读文件系统，无法写入文件

### ISSUE THREAD

**Issue by maxesisn** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#13]
设备为RT-AC1900P，华硕官方固件，使用自动脚本无法完成格式化，故手动安装，但第一次重启后无法在U盘内wget文件，也不能scp上传，管理页面不显示U盘

**Comment by z4jst** [comment]
U盘接到电脑完全格式化，格式化成 ext3 格式。手动模式下略去分区第一步，直接格式化。
再不行换个U盘试试。
另外取消挂载U盘可以使用 umount -l /dev/???
