### ISSUE TITLE
AC5300 无法运行 v2ray，提示 Illegal instruction

### ISSUE THREAD

**Issue by z4jst** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#23]
安装好，调整完配置文件，开启后monit一直报错。
手动运行后提示错误 ：Illegal instruction
查了一下资料，AC5300 CPU 是
ARMv7 Processor rev 0 (v7l)
说是阉割了 FPU ，导致无法运行 go 语言编写的程序。

https://github.com/v2ray/v2ray-core/issues/1977

想问一下大佬有什么解决办法么。

**Comment by z4jst** [comment]
使用最新go语言重新编译后使用正常。

**Comment by JACK-THINK** [comment]
由于Google更新了go编译器，导致使用参数`GOARCH=arm`编译时，默认使用`VFPv1`，但是armv7架构的华硕路由器被阉割了`VFPv1`，所以无法运行没有特殊处理过的预编译程序，报错`Illegal instruction`。（参阅https://github.com/v2ray/v2ray-core/issues/1988）

综上，本系统内一切使用go编译的程序均可能出现此问题，请等待各自官方的解决方案。

**Comment by diamondt5353** [comment]
大神，自己安装的程序怎么实现开机自启动

**Comment by JACK-THINK** [comment]
@diamondt5353 
看[使用说明](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/blob/master/How_to_Use_zh-CN.md)

**Comment by kslr** [comment]
尝试 4.22.0 该问题是否解决

**Comment by JACK-THINK** [comment]
@kslr 
在华硕RT-AC68U上实测v2ray-linux-arm.zip运行OK
