### ISSUE TITLE
SS官方已经舍弃obfs，建议用v2ray-plugin

### ISSUE THREAD

**Issue by eallion** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#25]

**Comment by JACK-THINK** [comment]
simple-obfs的优点是内存占用率超低，特别时候旧款低配置路由器。v2ray-plugin用go编译，内存占用较高，不适用于旧款低配置路由器。因此，在将来ss彻底不支持simple-obfs时，才会切换至v2ray-plugin
