### ISSUE TITLE
未挂载u盘

### ISSUE THREAD

**Issue by mrwangkis** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#3]
执行/tmp/mnt/ASUS_ROUTER/script_bootloader/bin/install。路由器自动重启后，SCRIPTS BOOTLOADER FOR ASUS ROUTER系统安装完毕

AC86u执行完这一步后 ssh进去/tmp/mnt/目录 没有ASUS_ROUTER这个文件夹啊 是不是不会自动挂载u盘

**Comment by JACK-THINK** [comment]
应该能自动挂载U盘。我的开发环境AC68U（原版梅林固件）和生产环境AC86U（原厂固件）都可以自动挂载，没有问题。

你的路由器是什么型号，用的什么固件，版本多少？请提供重启后的日志。
