### ISSUE TITLE
Clash插件

### ISSUE THREAD

**Issue by icetea0822** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#31]
您好：
    请问插件中能否制作一个Clash插件，现在Clash也越来越流行了，没有软路由真的很难搞，如果可以的话非常感谢！

**Comment by JACK-THINK** [comment]
@icetea0822 
实际上我早就计划添加clash插件了，但是不知道为什么clash作者至今也没发布clash稳定版（最新的版本是v0.16.0预发行版），因为不知道到clash的配置项或api是否已进入稳定期，所以我才没有添加clash插件。等第一个clash稳定版发布后再说吧

**Comment by icetea0822** [comment]
您好，我尝试自己装clash在我的86u上，我是梅林改版固件，为什么能打开tg微信之类的，网页全部打不开呢？dns那里都写了，透明代理应该也是成功了的，我tg直接就登进去了，就是网页不行

**Comment by JACK-THINK** [comment]
tg微信走到是UDP吧……网页不行因为走TCP。检查TCP转发配置

**Comment by icetea0822** [comment]
成功了之后发现手机游戏全都玩不了，放弃了哈哈，对iptables完全不懂，等大佬出插件再折腾了！感谢！
