### ISSUE TITLE
有些插件升级后又要重新配置的问题

### ISSUE THREAD

**Issue by magian1127** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#33]
我使用 cd /tmp && /tmp/mnt/ASUS_ROUTER/script_bootloader/bin/update 升级后
比如 ali_ddns 就失效了..又要重新配置才行..能设置升级后不要替换配置吗

**Comment by JACK-THINK** [comment]
@magian1127 现在不行，后续改进

**Comment by JACK-THINK** [comment]
@magian1127 
已解决
