### ISSUE TITLE
@fishredleung

### ISSUE THREAD

**Issue by guanzi008** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#35]
@fishredleung 
这个实在是没办法了。AdGuardHome官方的预编译版本AdGuardHome_linux_arm.tar.gz
不支持华硕路由器用的这种残缺的arm架构。已经有许多人在项目AdGuardHome中提了issue，等官方解决吧……

_Originally posted by @JACK-THINK in https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/issues/30#issuecomment-568159102_
加我https://t.me/odatacc
AdGuardHome
我应该能编译你需要的版本出来。

**Comment by fishredleung** [comment]
你運行腳本可以正常安裝麼？我卡在腳本SSL認證上面安裝不了

**Comment by guanzi008** [comment]
我在vps运行正常
dns.odata.cc

**Comment by guanzi008** [comment]
http://115.29.189.69:3333
