### ISSUE TITLE
Slow Downloading via Github

### ISSUE THREAD

**Issue by volatileAntiEntropy** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#36]
The Download of sbl_setup.tar.gz is very slow. The connection often dies during downloading.

**Comment by volatileAntiEntropy** [comment]
![2020-02-17](https://user-images.githubusercontent.com/45156039/74649845-5d0ba580-51bb-11ea-9e0d-a972bab484e5.png)
Log Here

**Comment by JACK-THINK** [comment]
看截屏您应该会说中文，那我就用中文回复了。

1. 您的网络环境可能在中国境内。不同运营商提供的网络会使连接GitHub的速度产生巨大差异，再加上国内网络环境对Github进行了“特殊照顾”，因此速度或快或慢是正常的，无法根治

2. 如果下载速度实在太慢，可以使用“离线安装”方法来解决问题
