### ISSUE TITLE
国内连接 github 下载速度感人，建议转为 gitee 下载

### ISSUE THREAD

**Issue by edwinhuish** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#39]
如题。

特别是在下载 releases 的时候，未知大小的压缩包，下了不到 6M 的压缩包，耗时10分钟。。。 且损坏了。。。。

然后又要重新在线安装，再次等待格式化U盘，又是大半个小时过去了。。。

建议自动化安装也加入一个格式化U盘选项。已格式化U盘的可以跳过格式化。

**Comment by JACK-THINK** [comment]
结论：不可能使用Gitee
原因：曾经测试过Gitee，发现它要求实名，只能说拜拜

更好的解决方法正在研究中，目前你可以用离线安装，比在线安装快得多
