### ISSUE TITLE
安装脚本执行时，/opt/bin/monit stop all 指令报错

### ISSUE THREAD

**Issue by cwh0704** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#40]
![1](https://user-images.githubusercontent.com/5860899/76154094-7d22ea80-6111-11ea-8525-4cdcc13def03.jpg)

如图，当安装脚本执行到addons_install 的 /opt/bin/monit stop all ，显示异常信息 /opt/etc/monitrc:160: syntax error

后续推出脚本后手动执行命令  /opt/bin/monit stop all 同样报错

**Comment by cwh0704** [comment]
将 /opt/etc/monitrc 中的登录用户名密码修改为双引号包围后，命令执行正常，且monit启动正常，web后台正常访问。根据官方文档，特殊字符也需要使用双引号包围

建议在后续脚本处理配置文件时，默认使用双引号

![2](https://user-images.githubusercontent.com/5860899/76154317-654d6580-6115-11ea-9de0-871eef65d8d9.jpg)

**Comment by JACK-THINK** [comment]
感谢反馈。此问题已修复，更新将于4月1日发布
