### ISSUE TITLE
(drive_modifier): 12454 NOTICE: CAN'T RE-PARTITION General UDisk 5.00 (install_online): 12228 FAILURE: ONLINE-INSTALL SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER

### ISSUE THREAD

**Issue by mgiftdc** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#42]
tmp# cd /tmp && wget -q -O /tmp/install_online --no-check-certificate "https://cdn.jsdelivr.net/gh/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTE
R@latest/script_bootloader/bin/install_online" && chmod 777 /tmp/install_online && /tmp/install_online
############### WARNING ###############
This program will erase ALL THE DATA on the target USB flash drive and install SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER.
Before installation, you must:
1. Back up all the data on the target USB flash drive.
2. Remove all the USB flash drives from the router except the target one.

############### 警告 ###############
本程序将清除目标U盘中全部数据并安装SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER。
开始安装前，请务必：
1. 备份目标U盘上的全部数据。
2. 除目标U盘外，移除全部连接至路由器的U盘。

Do you want to start installation right now? (YES/NO): YES
(install_online): 12228 INFO: START INSTALLATION
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2020-04-06 02:00:55--  https://cdn.jsdelivr.net/gh/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER@latest/script_bootloader/bin/drive_modifier
Resolving cdn.jsdelivr.net... 111.161.122.18, 111.206.179.93
Connecting to cdn.jsdelivr.net|111.161.122.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3740 (3.7K) [application/octet-stream]
Saving to: '/tmp/drive_modifier'

/tmp/drive_modifier                       100%[===================================================================================>]   3.65K  --.-KB/s    in 0.001s  

2020-04-06 02:00:55 (6.97 MB/s) - '/tmp/drive_modifier' saved [3740/3740]

(drive_modifier): 12454 INFO: RE-PARTITION General UDisk 5.00

The number of cylinders for this disk is set to 15000.
There is nothing wrong with that, but this is larger than 1024,
and could in certain setups cause problems with:
1) software that runs at boot time (e.g., old versions of LILO)
2) booting and partitioning software from other OSs
   (e.g., DOS FDISK, OS/2 FDISK)

Command (m for help): Changing display/entry units to sectors

Command (m for help): 
Disk /dev/sda: 15.7 GB, 15728640000 bytes
64 heads, 32 sectors/track, 15000 cylinders, total 30720000 sectors
Units = sectors of 1 * 512 = 512 bytes

   Device Boot      Start         End      Blocks  Id System
/dev/sda1            2048    30719999    15358976  83 Linux

Command (m for help): Building a new DOS disklabel. Changes will remain in memory only,
until you decide to write them. After that the previous content
won't be recoverable.

The number of cylinders for this disk is set to 15000.
There is nothing wrong with that, but this is larger than 1024,
and could in certain setups cause problems with:
1) software that runs at boot time (e.g., old versions of LILO)
2) booting and partitioning software from other OSs
   (e.g., DOS FDISK, OS/2 FDISK)

Command (m for help): Command action
   e   extended
   p   primary partition (1-4)
Partition number (1-4): First sector (32-30719999, default 32): Last sector or +size or +sizeM or +sizeK (2048-30719999, default 30719999): Using default value 30719999

Command (m for help): 
Disk /dev/sda: 15.7 GB, 15728640000 bytes
64 heads, 32 sectors/track, 15000 cylinders, total 30720000 sectors
Units = sectors of 1 * 512 = 512 bytes

   Device Boot      Start         End      Blocks  Id System
/dev/sda1            2048    30719999    15358976  83 Linux

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table
(drive_modifier): 12454 NOTICE: CAN'T RE-PARTITION General UDisk 5.00
(install_online): 12228 FAILURE: ONLINE-INSTALL SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER

**Comment by deechoe** [comment]
Hi Jack, 

I think the re-partition error comes from using the USB 3.0 port instead of 2.0.
