### ISSUE TITLE
卡在stage2

### ISSUE THREAD

**Issue by yilianziyu** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#44]
我的设备是r7000,固件版本是梅林384.15，离线安装卡在stage2,在install ENTWARE (success)后，提示HOME EXISTS、HOME IS MOUNTED，随后便报错：CAN'T LOCATE /opt/etc/init.d/rc.unslung。这是怎么回事？

**Comment by JACK-THINK** [comment]
本系统仅支持华硕路由器官方固件和梅林固件，不保证支持其他设备或第三方改版固件。因此无法提供解决方案。
