### ISSUE TITLE
v2ray插件的配置疑问

### ISSUE THREAD

**Issue by Heseli** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#49]
你好：
      我按照你的说明文档安装好了SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER并安装了v2ray插件。根据v2ray插件的说明，启动界面如下：

![home](https://user-images.githubusercontent.com/64262439/80214378-5131d900-866d-11ea-91d4-d631d6cb6861.png)
但完全无法上网，包括www.baidu.com也无法访问，必须关闭V2RAY_TRANSPARENT_PROXY才能正常上网，请问是什么问题呢？
      我已经按照v2ray插件的说明在/opt/script_bootloader/usr/v2ray/bin/fw_v2ray_transparent_proxy_enable.service文件中修改了参数TPROXY_MODULES_STATUS=false，请问还有哪个地方配置不对？v2ray配置文件我更改了outbounds中的vmess信息，inbounds不更改，这样正确么？
    期待你的回复，谢谢！

**Comment by JACK-THINK** [comment]
@Heseli 

对端的v2ray服务器配置正确吗？

**Comment by Heseli** [comment]
服务器端的v2ray应该是正常的，我用手机和电脑客户端都能正常连上使用。在路由器端的v2ray，我就是更改了/opt/ASUS_ROUTER/script_bootloader/usr/v2ray/etc下的config_proxy.json，配置的各个参数应该没有错，就不知道还有哪个地方出错了，我附上我的config_proxy.json，请帮忙查看一下，谢谢！

{
    "inbounds":
    [
        {
            "port":1080,
            "listen":"0.0.0.0",
            "protocol":"socks",
            "settings":
            {
                "auth":"noauth",
                "udp":true,
                "ip":"127.0.0.1",
                "userLevel":1
            },
            "tag":"LAN_inbound_socks_VPS"
        },
        {
            "port":2053,
            "listen":"0.0.0.0",
            "protocol":"dokodemo-door",
            "settings":
            {
                "address":"223.5.5.5",
                "port":53,
                "network":"tcp,udp",
                "timeout":0,
                "followRedirect":false,
                "userLevel":1
            },
            "tag":"DNS_local_dokodemo_VPS"
        },
        {
            "port":45154,
            "listen":"0.0.0.0",
            "protocol":"dokodemo-door",
            "settings":
            {
                "network":"tcp,udp",
                "timeout":30,
                "followRedirect":true,
                "userLevel":1
            },
            "streamSettings":
            {
                "sockopt":
                {
                    "tproxy":"redirect"
                }
            },
            "tag":"LAN_local_dokodemo_VPS"
        },
        {
            "port":22815
            "listen":"",
            "protocol":"vmess",
            "settings":
            {
                "clients":
                [
                    {
                        "id":"",
                        "level":1,
                        "alterId":64
                    }
                ],
                "disableInsecureEncryption":true
            },
            "streamSettings":
            {
                "network":"tcp",
                "security":"none",
                "tcpSettings":
                {
                    "header":
                    {
                        "type":"http",
                        "request":
                        {
                            "version":"1.1",
                            "method":"GET",
                            "path":
                            [
                                "/"
                            ],
                            "headers":
                            {
                                "Host":
                                [
                                    "www.163.com",
                                    "www.baidu.com",
                                    "www.cctv.com",
                                    "www.jd.com",
                                    "www.qq.com",
                                    "www.sina.com.cn",
                                    "www.taobao.com",
                                    "www.bing.com",
                                    "www.alibaba.com"
                                ],
                                "User-Agent":
                                [
                                    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
                                    "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                                ],
                                "Accept-Encoding":
                                [
                                    "gzip, deflate"
                                ],
                                "Connection":
                                [
                                    "keep-alive"
                                ],
                                "Pragma":"no-cache"
                            }
                        },
                        "response":
                        {
                            "version":"1.1",
                            "status":"200",
                            "reason":"OK",
                            "headers":
                            {
                                "Content-Type":
                                [
                                    "application/octet-stream",
                                    "video/mpeg"
                                ],
                                "Transfer-Encoding":
                                [
                                    "chunked"
                                ],
                                "Connection":
                                [
                                    "keep-alive"
                                ],
                                "Pragma":"no-cache"
                            }
                        }
                    }
                }
            },
            "tag":"WAN_inbound_vmess_VPS"
        },
        {
            "port":22816,
            "listen":"0.0.0.0",
            "protocol":"shadowsocks",
            "settings":
            {
                "method":"aes-256-gcm",
                "password":"",
                "level":1,
                "ota":false,
                "network":"tcp,udp"
            },
            "tag":"WAN_inbound_shadowsocks_VPS"
        },
        {
            "port":22817,
            "listen":"0.0.0.0",
            "protocol":"vmess",
            "settings":
            {
                "clients":
                [
                    {
                        "id":"",
                        "level":1,
                        "alterId":64
                    }
                ],
                "disableInsecureEncryption":true
            },
            "streamSettings":
            {
                "network":"tcp",
                "security":"none",
                "tcpSettings":
                {
                    "header":
                    {
                        "type":"http",
                        "request":
                        {
                            "version":"1.1",
                            "method":"GET",
                            "path":
                            [
                                "/"
                            ],
                            "headers":
                            {
                                "Host":
                                [
                                    "www.163.com",
                                    "www.baidu.com",
                                    "www.cctv.com",
                                    "www.jd.com",
                                    "www.qq.com",
                                    "www.sina.com.cn",
                                    "www.taobao.com",
                                    "www.bing.com",
                                    "www.alibaba.com"
                                ],
                                "User-Agent":
                                [
                                    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
                                    "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                                ],
                                "Accept-Encoding":
                                [
                                    "gzip, deflate"
                                ],
                                "Connection":
                                [
                                    "keep-alive"
                                ],
                                "Pragma":"no-cache"
                            }
                        },
                        "response":
                        {
                            "version":"1.1",
                            "status":"200",
                            "reason":"OK",
                            "headers":
                            {
                                "Content-Type":
                                [
                                    "application/octet-stream",
                                    "video/mpeg"
                                ],
                                "Transfer-Encoding":
                                [
                                    "chunked"
                                ],
                                "Connection":
                                [
                                    "keep-alive"
                                ],
                                "Pragma":"no-cache"
                            }
                        }
                    }
                }
            },
            "tag":"WAN_inbound_vmess_Router"
        },
        {
            "port":22818,
            "listen":"0.0.0.0",
            "protocol":"shadowsocks",
            "settings":
            {
                "method":"aes-256-gcm",
                "password":"",
                "level":1,
                "ota":false,
                "network":"tcp,udp"
            },
            "tag":"WAN_inbound_shadowsocks_Router"
        }
    ],
    "outbounds":
    [
        {
            "sendThrough":"0.0.0.0",
            "protocol":"vmess",
            "settings":
            {
                "vnext":
                [
                    {
                        "address":"103.x.x.152",
                        "port":14109,
                        "users":
                        [
                            {
                                "id":"da265348-427d-4624-9476-xxxxxxxxxx",
                                "alterid":233,
                                "security":"auto",
                                "level":1
                            }
                        ]
                    }
                ]
            },
            "streamSettings":
            {
                "network":"tcp",
                "security":"none",
                "tcpSettings":
                {
                    "header":
                    {
                        "type":"http",
                        "request":
                        {
                            "version":"1.1",
                            "method":"GET",
                            "path":
                            [
                                "/"
                            ],
                            "headers":
                            {
                                "Host":
                                [
                                    "www.163.com",
                                    "www.baidu.com",
                                    "www.cctv.com",
                                    "www.jd.com",
                                    "www.qq.com",
                                    "www.sina.com.cn",
                                    "www.taobao.com",
                                    "www.bing.com",
                                    "www.alibaba.com"
                                ],
                                "User-Agent":
                                [
                                    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
                                    "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                                ],
                                "Accept-Encoding":
                                [
                                    "gzip, deflate"
                                ],
                                "Connection":
                                [
                                    "keep-alive"
                                ],
                                "Pragma":"no-cache"
                            }
                        },
                        "response":
                        {
                            "version":"1.1",
                            "status":"200",
                            "reason":"OK",
                            "headers":
                            {
                                "Content-Type":
                                [
                                    "application/octet-stream",
                                    "video/mpeg"
                                ],
                                "Transfer-Encoding":
                                [
                                    "chunked"
                                ],
                                "Connection":
                                [
                                    "keep-alive"
                                ],
                                "Pragma":"no-cache"
                            }
                        }
                    }
                }
            },
            "tag":"VPS_outbound"
        },
        {
            "sendThrough":"0.0.0.0",
            "protocol":"freedom",
            "settings":
            {
                "domainStrategy":"AsIs",
                "userLevel":1
            },
            "tag":"Router_outbound"
        }
    ],
    "routing":
    {
        "domainStrategy":"AsIs",
        "rules":
        [
            {
                "type":"field",
                "inboundTag":
                [
                    "LAN_inbound_socks_VPS"
                ],
                "outboundTag":"VPS_outbound"
            },
            {
                "type":"field",
                "inboundTag":
                [
                    "DNS_local_dokodemo_VPS"
                ],
                "outboundTag":"VPS_outbound"
            },
            {
                "type":"field",
                "inboundTag":
                [
                    "LAN_local_dokodemo_VPS"
                ],
                "outboundTag":"VPS_outbound"
            },
            {
                "type":"field",
                "inboundTag":
                [
                    "WAN_inbound_vmess_VPS"
                ],
                "outboundTag":"VPS_outbound"
            },
            {
                "type":"field",
                "inboundTag":
                [
                    "WAN_inbound_shadowsocks_VPS"
                ],
                "outboundTag":"VPS_outbound"
            },
            {
                "type":"field",
                "inboundTag":
                [
                    "WAN_inbound_vmess_Router"
                ],
                "outboundTag":"Router_outbound"
            },
            {
                "type":"field",
                "inboundTag":
                [
                    "WAN_inbound_shadowsocks_Router"
                ],
                "outboundTag":"Router_outbound"
            }
        ]
    },
    "policy":
    {
        "levels":
        {
            "1":
            {
                "handshake":4,
                "connIdle":300,
                "uplinkOnly":2,
                "downlinkOnly":5,
                "statsUserUplink":false,
                "statsUserDownlink":false
            }
        }
    }
}

**Comment by JACK-THINK** [comment]
@Heseli 
这个格式实在是一言难尽啊……
你直接运行`/tmp/mnt/ASUS_ROUTER/script_bootloader/usr/v2ray/bin/v2ray_configure`，按照屏幕提示再重新配置一遍试试吧

**Comment by Heseli** [comment]
Hi:
    我重新运行了v2ray_configure,仍然无法正常上网（只要启动了V2RAY_TRANSPARENT_PROXY就无法上网，连百度也上不了，只能关闭）。我的v2ray配置一再确认过应该没有问题。怀疑是不是更改/opt/script_bootloader/usr/v2ray/bin/fw_v2ray_transparent_proxy_enable.service 第86行为TPROXY_MODULES_STATUS=false这一项有错误？我提供一下目前我的路由器上这个文件目前的截图，请帮我确认一下是否更改正确，谢谢！

![1](https://user-images.githubusercontent.com/64262439/81031112-be3f3d00-8ebd-11ea-858c-513a27d3c168.png)

**Comment by JACK-THINK** [comment]
@Heseli 

果然这里有问题。把现有“/opt/script_bootloader/usr/v2ray/bin/fw_v2ray_transparent_proxy_enable.service”的第86行改为`########## CHECK TPROXY MODULES ##########`，把第90行中`true`改为`false`，其它都不要动。试试这样改能否解决问题

**Comment by Heseli** [comment]
很遗憾，更改了之后还是无法上网，唉。
