### ISSUE TITLE
(install_online): 16664 NOTICE: sbl_setup.tar.gz IS CORRUPT

### ISSUE THREAD

**Issue by iPatrickW** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#52]
`/tmp/mnt/ASUS_ROUTER/sbl_setup.tar.gz     [          <=>                                                             ]   5.73M  28.8KB/s    in 4m 8s   

2020-04-25 14:53:16 (23.6 KB/s) - '/tmp/mnt/ASUS_ROUTER/sbl_setup.tar.gz' saved [6006281]

(install_online): 16664 NOTICE: sbl_setup.tar.gz IS CORRUPT
(install_online): 16664 FAILURE: ONLINE-INSTALL SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER`

**Comment by JACK-THINK** [comment]
Github被ISP污染，换用离线安装
