### ISSUE TITLE
离线安装卡在LOAD DNSMASQ.D

### ISSUE THREAD

**Issue by iPatrickW** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#53]
`(dnsmasq.d_install): 25800 SUCCESS: INSTALL DNSMASQ.D

Done.
LOAD DNSMASQ.D
(install): 4070 FAILURE: STAGE 2`

**Comment by JACK-THINK** [comment]
@iPatrickW 

这是一个发生率很低的Bug，现已修复
