### ISSUE TITLE
shadowsocks client | server 该填什么？

### ISSUE THREAD

**Issue by iPatrickW** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#56]
`(shadowsocks_configure): 4982 INFO: ROLE: client | server
(shadowsocks_configure): 4982 INFO: INPUT THE VALUE: 
`
server我知道，client填什么，中间要加｜吗？

**Comment by JACK-THINK** [comment]
这是让你从`client`和`server`两个**值**中选一个填写
