### ISSUE TITLE
请问支持ax89x吗?

### ISSUE THREAD

**Issue by RickGanKL** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#58]
您好，请问支持ax89x吗？ 
谢谢

**Comment by JACK-THINK** [comment]
@RickGanKL 

我没有RT-AX89X，你可以试试

**Comment by RickGanKL** [comment]
@JACK-THINK 谢谢你的回复
我准备开始安装了，我这版离线安装的时候，发现链接失效了，能补一下吗？
谢谢
https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E7%B4%A2%E5%BC%95#Entware%E7%A6%BB%E7%BA%BF%E5%BA%93

**Comment by JACK-THINK** [comment]
@RickGanKL 

用离线安装那个链接，没失效啊。
