### ISSUE TITLE
请问下到这一步应该怎么办？

### ISSUE THREAD

**Issue by eating521** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#73]
@JACK-THINK 
(swap_configure): 9093 INFO: SWAP SIZE (MB): 256 | 512 | 1024 | 2048
到这一步的时候就停止执行脚本了。请问该怎么办呢

**Comment by eating521** [comment]
![QQ截图20200830003008](https://user-images.githubusercontent.com/40644549/91641650-67570800-ea58-11ea-9e6f-36d4bca986db.png)

**Comment by yifan237** [comment]
如如你要设定的虚拟内存大小，上面四个根据自己需求输入一个，建议至少512起
