### ISSUE TITLE
U 盘换了一个口重启后不能正常工作了

### ISSUE THREAD

**Issue by nauxliu** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#74]
型号：AC68U
问题描述：
我将 U 盘从 USB3.0 插口拔下来换到了 USB 2.0，发现所有服务都不能正常工作了, 换回了 USB3.0 插口还是不行。
看起来 U 盘没有被挂载到 `/opt` 。

还需要我提供什么日志信息方便分析吗？

**Comment by nauxliu** [comment]
发现原因和 #65 一样，`script_bootloader_usb_mount ` 没有了任何权限，手动给权限后重启路由器，还是不能正常工作，一看文件又没权限了。

```
chmod 777 script_bootloader_usb_mount
reboot now
```

**Comment by JACK-THINK** [comment]
@nauxliu 
这是防止同时使用多个U盘导致多次加载本系统的锁机制。你在系统加载完毕（即取消锁）之前就重启路由器了，才会导致此问题。阅读[源码](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/blob/master/script_bootloader/bin/script_bootloader_usb_mount)
