### ISSUE TITLE
关于离线安装的小白提问

### ISSUE THREAD

**Issue by Naldobb** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#78]
@JACK-THINK 在线安装失败，看到解决方案貌似只有离线一条路可以走。
但是关于上传到/tmp/home/root这一步很困惑。用ftp看不到有此路径，难道是直接创建这个路径然后上传吗？

**Comment by leechaojie** [comment]
ftp是不行的，打开终端（不用登陆路由器后台） 输入以下代码从本地上传到路由器
`scp -P 22 C:/Users/admin/Desktop/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER-17.0-17.0.tar.gz username@192.168.x.x:/tmp/home/root`
`-P 22`表示你的路由器后台的端口号
`C:/Users/admin/Desktop/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER-17.0-17.0.tar.gz `表示你的离线包所在的路径
`username@192.168.x.x:/tmp/home/root`表示你路由器的username，ip地址，
复制代码，按需修改就可以上传成功。
