### ISSUE TITLE
请问怎么实现官方固件开机自动运行USB脚本的？

### ISSUE THREAD

**Issue by champagneo** [JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER#96]
作者你好，你写的脚本非常完美。

但我只需要使用U盘跑一个小服务，使用整套系统对于我的老旧路由器来说还是太臃肿了。

特来讨教下如何实现官方固件开机自动运行USB里的一个脚本的？我曾尝试按照教程 https://irq5.io/2018/12/28/extending-asuswrt-functionality-part-2/ 但是还是不行，不知道你用的是哪种方法？

谢谢！

**Comment by edwinhuish** [comment]
我查看了一下他的install脚本，实现开机启动主要是下面这段：
![image](https://user-images.githubusercontent.com/5207925/154439691-5d67c63a-3c23-436c-8db0-9aa7e8b0765f.png)

**Comment by champagneo** [comment]
谢谢。过程大概是
`nvram set script_usbmount /path/your/usb/device`

**Comment by champagneo** [comment]
So sad...

Hope the next version will support.
